language: go
go:
  - "1.12"
services:
  - docker

env: GO111MODULE=on

install:
  - make vendor

before_script:
  - go vet ./...
  - go build ./...
  - go test -run xxxx ./...

script:
  - go fmt ./...
  - go run golang.org/x/lint/golint $(go list ./... | grep -v /vendor/) # golint doesn't ignore vendor  - go test -race -short -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false 
