// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signed_message.proto

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	signed_message.proto

It has these top-level messages:
	SignedPaymentMessage
*/
package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignedPaymentMessage struct {
	H       string `protobuf:"bytes,1,opt,name=h" json:"h,omitempty"`
	R       string `protobuf:"bytes,2,opt,name=r" json:"r,omitempty"`
	S       string `protobuf:"bytes,3,opt,name=s" json:"s,omitempty"`
	V       string `protobuf:"bytes,4,opt,name=v" json:"v,omitempty"`
	Address string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	Hash    string `protobuf:"bytes,6,opt,name=hash" json:"hash,omitempty"`
	Sig     string `protobuf:"bytes,7,opt,name=sig" json:"sig,omitempty"`
}

func (m *SignedPaymentMessage) Reset()                    { *m = SignedPaymentMessage{} }
func (m *SignedPaymentMessage) String() string            { return proto.CompactTextString(m) }
func (*SignedPaymentMessage) ProtoMessage()               {}
func (*SignedPaymentMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SignedPaymentMessage) GetH() string {
	if m != nil {
		return m.H
	}
	return ""
}

func (m *SignedPaymentMessage) GetR() string {
	if m != nil {
		return m.R
	}
	return ""
}

func (m *SignedPaymentMessage) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *SignedPaymentMessage) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *SignedPaymentMessage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SignedPaymentMessage) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *SignedPaymentMessage) GetSig() string {
	if m != nil {
		return m.Sig
	}
	return ""
}

func init() {
	proto.RegisterType((*SignedPaymentMessage)(nil), "models.signed_payment_message")
}

func init() { proto.RegisterFile("signed_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0xc1, 0x0a, 0xc2, 0x30,
	0x0c, 0xc6, 0x71, 0xea, 0xe6, 0x86, 0xc1, 0x83, 0x04, 0x91, 0x1c, 0xc5, 0x93, 0x27, 0x2f, 0xbe,
	0x89, 0x2f, 0x20, 0x95, 0x86, 0x76, 0x60, 0xd7, 0xd1, 0x8c, 0x81, 0x6f, 0xe1, 0x23, 0x4b, 0x53,
	0x77, 0xcb, 0xef, 0xcf, 0x77, 0x08, 0x1c, 0x65, 0xf0, 0x23, 0xbb, 0x67, 0x64, 0x11, 0xeb, 0xf9,
	0x36, 0xe5, 0x34, 0x27, 0xec, 0x62, 0x72, 0xfc, 0x96, 0xcb, 0xd7, 0xc0, 0xe9, 0x3f, 0x98, 0xec,
	0x27, 0xf2, 0x38, 0xaf, 0x43, 0xdc, 0x83, 0x09, 0x64, 0xce, 0xe6, 0xba, 0x7b, 0x98, 0x50, 0x94,
	0x69, 0x53, 0x95, 0x8b, 0x84, 0x9a, 0x2a, 0x29, 0x5a, 0xa8, 0xad, 0x5a, 0x90, 0xa0, 0xb7, 0xce,
	0x65, 0x16, 0xa1, 0xad, 0xb6, 0x95, 0x88, 0xd0, 0x06, 0x2b, 0x81, 0x3a, 0xcd, 0x7a, 0xe3, 0x01,
	0x1a, 0x19, 0x3c, 0xf5, 0x9a, 0xca, 0xf9, 0xea, 0xf4, 0xc3, 0xfb, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x35, 0x56, 0x6d, 0x1e, 0xb9, 0x00, 0x00, 0x00,
}
